In [1]:

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
#Reading Toothcaries dataset
data = pd.read_csv('ToothCarriesPCADataset1.csv')

In [3]:
#Reading Toothcaries dataset first ten rows
data.head(10)

act_caries  Gender  Prev_caries  Calculus  Fluorosis  Bleeding  X1  X2  X3  \
0           0       1            0         1          0         0   0   0   1   
1           1       0            0         1          0         1   1   0   0   
2           1       0            1         1          0         1   0   1   0   
3           0       0            1         1          0         1   1   1   0   
4           0       0            0         0          1         0   0   0   1   
5           0       1            0         1          1         0   0   0   0   
6           1       1            1         0          0         1   0   0   0   
7           0       0            0         0          1         0   1   0   1   
8           0       1            0         1          0         0   0   1   0   
9           1       0            0         0          1         1   1   1   0   

   X4_1  ...  X13  X14_1  X14_2  X14_3  X14_4  X14_5  X14_6  X14_7  X14_8  \
0     0  ...    1      0      1      1      0      1      0      0      1   
1     0  ...    1      0      0      1      0      1      0      0      0   
2     1  ...    1      0      1      1      1      0      0      0      0   
3     0  ...    1      1      1      0      1      1      1      0      0   
4     0  ...    0      0      0      0      1      0      0      1      1   
5     0  ...    0      1      0      0      0      1      0      0      1   
6     0  ...    1      0      0      0      1      1      0      1      1   
7     0  ...    0      1      1      0      1      0      0      1      0   
8     1  ...    0      1      1      1      1      1      0      1      1   
9     0  ...    1      1      1      0      1      1      0      0      1   

   X14_9  
0      1  
1      0  
2      0  
3      0  
4      0  
5      1  
6      0  
7      1  
8      0  
9      1  

[10 rows x 35 columns]

In [4]:
#Checking Toothcaries dataset missing values
data.isnull().sum()

act_caries     0
Gender         0
Prev_caries    0
Calculus       0
Fluorosis      0
Bleeding       0
X1             0
X2             0
X3             0
X4_1           0
X4_2           0
X4_3           0
X4_4           0
X4_5           0
X4_6           0
X4_7           0
X4_8           0
X4_9           0
X6             0
X7             0
X8             0
X9             0
X10            0
X11            0
X12            0
X13            0
X14_1          0
X14_2          0
X14_3          0
X14_4          0
X14_5          0
X14_6          0
X14_7          0
X14_8          0
X14_9          0
dtype: int64

In [5]:
#information of Toothcaries dataset
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10549 entries, 0 to 10548
Data columns (total 35 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   act_caries   10549 non-null  int64
 1   Gender       10549 non-null  int64
 2   Prev_caries  10549 non-null  int64
 3   Calculus     10549 non-null  int64
 4   Fluorosis    10549 non-null  int64
 5   Bleeding     10549 non-null  int64
 6   X1           10549 non-null  int64
 7   X2           10549 non-null  int64
 8   X3           10549 non-null  int64
 9   X4_1         10549 non-null  int64
 10  X4_2         10549 non-null  int64
 11  X4_3         10549 non-null  int64
 12  X4_4         10549 non-null  int64
 13  X4_5         10549 non-null  int64
 14  X4_6         10549 non-null  int64
 15  X4_7         10549 non-null  int64
 16  X4_8         10549 non-null  int64
 17  X4_9         10549 non-null  int64
 18  X6           10549 non-null  int64
 19  X7           10549 non-null  int64
 20  X8    

In [ ]:
from sklearn.ensemble import RandomForestClassifier

y=data["act_caries"]
x=data.drop(["act_caries"], axis=1)
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
le = preprocessing.LabelEncoder()

In [ ]:
#all features without PCA data
from sklearn.metrics import accuracy_score
import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier, GradientBoostingClassifier
print("RF")
rfc = RandomForestClassifier(n_estimators=100, random_state=52)
pred = rfc.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,pred))
print("ADA")
xgb = AdaBoostClassifier(n_estimators=100, random_state=52)
xgb_pred = xgb.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,xgb_pred))
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,classification_report
dt = DecisionTreeClassifier(random_state=50)
print("Decision Tree Classifier Result")
DecisionTree=dt.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,DecisionTree))
from sklearn.svm import SVC
print("SVC")
svm = SVC(kernel='linear', C=2.0, random_state=52)
svm.fit(X_train,y_train)
y_pred=svm.predict(X_test)
print(accuracy_score(y_test,y_pred))
print("ETC")
b = ExtraTreesClassifier(n_estimators=100, random_state=52)
b_pred = b.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,b_pred))
from sklearn.naive_bayes import MultinomialNB
print("MultinomialNB NB")
gnb = MultinomialNB()
gnb_pred = gnb.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,gnb_pred))
# Fitting XGBoost to the training data
XGBClassifier = xgb.XGBClassifier()
XGBoost=my_model.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,XGBoost))
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
print("Logistic Regression Result")
logisticRegresion=lr.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,logisticRegresion))

from sklearn.calibration import CalibratedClassifierCV
from sklearn.linear_model import SGDClassifier
print("Stochastic Gradient Classifier")
clf = SGDClassifier(max_iter=1100, tol=1e-3)
calibrated_clf = CalibratedClassifierCV(clf, cv=5, method='isotonic')
predSGD=calibrated_clf.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,predSGD))

#from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier
#from sklearn.linear_model import SGDClassifier
print("Voting Classifier XGB+RF+ETC")
clf1 = xgb.XGBClassifier()
clf2 = RandomForestClassifier(n_estimators=100, random_state=52)
clf3 = ExtraTreesClassifier(n_estimators=100, random_state=52)
eclf1 = VotingClassifier(estimators=[
        ('xgb', clf1), ('rf', clf2), ('etc', clf3)],voting='hard')
predictionVC=eclf1.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,predictionVC))

In [ ]:
# Splitting dataset into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, shuffle=True)

In [ ]:
len(y_train)

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(max_depth=50)
dtPre=dt.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,dtPre))
print(classification_report(y_test,dtPre))
print(confusion_matrix(y_test,dtPre))

In [ ]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
print("ADA")
xgb = AdaBoostClassifier(n_estimators=200, random_state=5)
xgb_pred = xgb.fit(X_train, y_train).predict(X_test)
print(classification_report(y_test,xgb_pred))
print(confusion_matrix(y_test,xgb_pred))

In [ ]:
from sklearn.svm import SVC
print("SVC")
svm = SVC(kernel='linear', C=1.0, random_state=500)
svm.fit(X_train,y_train)
y_pred=svm.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))


In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=200, random_state=5, max_depth=20)
rfc.fit(X_train, y_train)
# calculate accuracy of class predictions
y_pred_class = rfc.predict(X_test)
print(classification_report(y_test,y_pred_class))
print(confusion_matrix(y_test,y_pred_class))

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
print("ETC")
b = ExtraTreesClassifier(n_estimators=200, random_state=5, max_depth=20)
b_pred = b.fit(X_train, y_train).predict(X_test)
print(classification_report(y_test,b_pred))
print(confusion_matrix(y_test,b_pred))

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
# 2. instantiate a logistic regression model
logreg = LogisticRegression(random_state=1000, solver='liblinear',multi_class='ovr',C=3.0)
# 3. train the model using X_train_dtm
x=logreg.fit(X_train, y_train)
# 4. make class predictions for X_test_dtm
y_pred_class = logreg.predict(X_test)
print(classification_report(y_test,y_pred_class))
print(confusion_matrix(y_test,y_pred_class))


In [ ]:
from sklearn.linear_model import SGDClassifier
r3=SGDClassifier(max_iter=1000, tol=1e-3,loss='perceptron')
x=r3.fit(X_train, y_train)

y_pred_class = r3.predict(X_test)
print(classification_report(y_test,y_pred_class))
print(confusion_matrix(y_test,y_pred_class))


In [ ]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
r1 = LogisticRegression(random_state=1000, solver='liblinear',multi_class='ovr',C=3.0)
r2 = SVC(kernel='linear', C=1.0, random_state=500,probability=True)
r3 = SGDClassifier(max_iter=1000, tol=1e-3,loss='perceptron')
er = VotingClassifier([('lr', r1),('svc', r2),('sgdc', r3)],voting="hard")

x=er.fit(X_train, y_train)

y_pred_class = er.predict(X_test)
print(classification_report(y_test,y_pred_class))
print(confusion_matrix(y_test,y_pred_class))


In [ ]:
import numpy as np # linear algebra

import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
import glob
import cv2
import tensorflow as tf
from keras import layers
from keras.layers import Dropout , Input, Add, Dense, Activation, ZeroPadding2D, BatchNormalization, Flatten, Conv2D, AveragePooling2D, MaxPooling2D, GlobalMaxPooling2D
from keras.models import Model, load_model
from keras.initializers import glorot_uniform
from sklearn.model_selection import train_test_split
import keras.backend as K
from sklearn.utils import shuffle
# importing all necessary libraries to run the code
import re,string
import numpy as np
import pandas as pd
import keras_metrics
import tensorflow.keras
import matplotlib.pyplot as plt
from nltk.corpus import stopwords
from keras.models import Sequential
from sklearn.model_selection import train_test_split
from keras.layers import Dense, Flatten, LSTM, Conv1D, MaxPooling1D, Dropout, Activation,Embedding
# using the variable sw to hold all stopwords that are in English
sw = stopwords.words('english')

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le = preprocessing.LabelEncoder()
y = le.fit_transform(target)

In [ ]:
X_train_res=df.astype(int)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(max_depth=50)
dtPre=dt.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,dtPre))
print(classification_report(y_test,dtPre))
print(confusion_matrix(y_test,dtPre))

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=200, random_state=5, max_depth=20)
rfc.fit(X_train, y_train)
# calculate accuracy of class predictions
y_pred_class = rfc.predict(X_test)
print(classification_report(y_test,y_pred_class))
print(confusion_matrix(y_test,y_pred_class))

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
print("ETC")
b = ExtraTreesClassifier(n_estimators=300, random_state=5, max_depth=20)
b_pred = b.fit(X_train, y_train).predict(X_test)
print(classification_report(y_test,b_pred))
print(confusion_matrix(y_test,b_pred))

In [ ]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
print("ADA")
xgb = AdaBoostClassifier(n_estimators=100, random_state=5)
xgb_pred = xgb.fit(X_train, y_train).predict(X_test)
print(classification_report(y_test,xgb_pred))
print(confusion_matrix(y_test,xgb_pred))

In [ ]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
r1 = LogisticRegression(random_state=1000, solver='saga',multi_class='ovr',C=2.0)
r2 = SVC(kernel='linear', C=1.0, random_state=2, probability=True)
r3=SGDClassifier(loss='perceptron')
er = VotingClassifier([('svc', r2),('lr', r1),('sgdc', r3)],voting="hard")

x=er.fit(X_train, y_train)

y_pred_class = er.predict(X_test)
print(classification_report(y_test,y_pred_class))
print(confusion_matrix(y_test,y_pred_class))

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
# 2. instantiate a logistic regression model
logreg = LogisticRegression(random_state=1000, solver='saga',multi_class='ovr',C=2.0)
# 3. train the model using X_train_dtm
x=logreg.fit(X_train, y_train)
# 4. make class predictions for X_test_dtm
y_pred_class = logreg.predict(X_test)
print(classification_report(y_test,y_pred_class))
print(confusion_matrix(y_test,y_pred_class))


              precision    recall  f1-score   support

           0       0.81      0.81      0.81        26
           1       0.86      0.86      0.86        35

    accuracy                           0.84        61
   macro avg       0.83      0.83      0.83        61
weighted avg       0.84      0.84      0.84        61

[[21  5]
 [ 5 30]]


In [ ]:
from sklearn.svm import SVC
print("SVC")
svm = SVC(kernel='sigmoid', C=1.0, random_state=2)
svm.fit(X_train,y_train)
y_pred=svm.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

SVC
              precision    recall  f1-score   support

           0       0.79      0.85      0.81        26
           1       0.88      0.83      0.85        35

    accuracy                           0.84        61
   macro avg       0.83      0.84      0.83        61
weighted avg       0.84      0.84      0.84        61

[[22  4]
 [ 6 29]]


In [ ]:
#PCA feature data
from sklearn.metrics import accuracy_score
import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier, GradientBoostingClassifier
print("RF")
rfc = RandomForestClassifier(n_estimators=100, random_state=52)
pred = rfc.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,pred))
print("ADA")
xgb = AdaBoostClassifier(n_estimators=100, random_state=52)
xgb_pred = xgb.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,xgb_pred))
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,classification_report
dt = DecisionTreeClassifier(random_state=50)
print("Decision Tree Classifier Result")
DecisionTree=dt.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,DecisionTree))
from sklearn.svm import SVC
print("SVC")
svm = SVC(kernel='linear', C=2.0, random_state=52)
svm.fit(X_train,y_train)
y_pred=svm.predict(X_test)
print(accuracy_score(y_test,y_pred))
print("ETC")
b = ExtraTreesClassifier(n_estimators=100, random_state=52)
b_pred = b.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,b_pred))
from sklearn.naive_bayes import MultinomialNB
print("MultinomialNB NB")
gnb = MultinomialNB()
gnb_pred = gnb.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,gnb_pred))
# Fitting XGBoost to the training data
XGBClassifier = xgb.XGBClassifier()
XGBoost=my_model.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,XGBoost))
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
print("Logistic Regression Result")
logisticRegresion=lr.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,logisticRegresion))

from sklearn.calibration import CalibratedClassifierCV
from sklearn.linear_model import SGDClassifier
print("Stochastic Gradient Classifier")
clf = SGDClassifier(max_iter=1100, tol=1e-3)
calibrated_clf = CalibratedClassifierCV(clf, cv=5, method='isotonic')
predSGD=calibrated_clf.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,predSGD))

#from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier
#from sklearn.linear_model import SGDClassifier
print("Voting Classifier XGB+RF+ETC")
clf1 = xgb.XGBClassifier()
clf2 = RandomForestClassifier(n_estimators=100, random_state=52)
clf3 = ExtraTreesClassifier(n_estimators=100, random_state=52)
eclf1 = VotingClassifier(estimators=[
        ('xgb', clf1), ('rf', clf2), ('etc', clf3)],voting='hard')
predictionVC=eclf1.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,predictionVC))

In [ ]:
#PCA features data
from sklearn.metrics import accuracy_score
import xgboost as xgb
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, ExtraTreesClassifier, GradientBoostingClassifier
print("RF")
rfc = RandomForestClassifier(n_estimators=100, random_state=52)
pred = rfc.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,pred))
print("ADA")
xgb = AdaBoostClassifier(n_estimators=100, random_state=52)
xgb_pred = xgb.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,xgb_pred))
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,classification_report
dt = DecisionTreeClassifier(random_state=50)
print("Decision Tree Classifier Result")
DecisionTree=dt.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,DecisionTree))
from sklearn.svm import SVC
print("SVC")
svm = SVC(kernel='linear', C=2.0, random_state=52)
svm.fit(X_train,y_train)
y_pred=svm.predict(X_test)
print(accuracy_score(y_test,y_pred))
print("ETC")
b = ExtraTreesClassifier(n_estimators=100, random_state=52)
b_pred = b.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,b_pred))
from sklearn.naive_bayes import MultinomialNB
print("MultinomialNB NB")
gnb = MultinomialNB()
gnb_pred = gnb.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,gnb_pred))
# Fitting XGBoost to the training data
XGBClassifier = xgb.XGBClassifier()
XGBoost=my_model.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,XGBoost))
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
print("Logistic Regression Result")
logisticRegresion=lr.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,logisticRegresion))

from sklearn.calibration import CalibratedClassifierCV
from sklearn.linear_model import SGDClassifier
print("Stochastic Gradient Classifier")
clf = SGDClassifier(max_iter=1100, tol=1e-3)
calibrated_clf = CalibratedClassifierCV(clf, cv=5, method='isotonic')
predSGD=calibrated_clf.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,predSGD))

#from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier
#from sklearn.linear_model import SGDClassifier
print("Voting Classifier XGB+RF+ETC")
clf1 = xgb.XGBClassifier()
clf2 = RandomForestClassifier(n_estimators=100, random_state=52)
clf3 = ExtraTreesClassifier(n_estimators=100, random_state=52)
eclf1 = VotingClassifier(estimators=[
        ('xgb', clf1), ('rf', clf2), ('etc', clf3)],voting='hard')
predictionVC=eclf1.fit(X_train, y_train).predict(X_test)
print(accuracy_score(y_test,predictionVC))

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
# 2. instantiate a logistic regression model
logreg = LogisticRegression(random_state=1000, solver='saga',multi_class='ovr',C=2.0)
# 3. train the model using X_train_dtm
x=logreg.fit(X_train, y_train)
# 4. make class predictions for X_test_dtm
y_pred_class = logreg.predict(X_test)
print(classification_report(y_test,y_pred_class))
print(confusion_matrix(y_test,y_pred_class))


              precision    recall  f1-score   support

           0       0.94      0.85      0.89        93
           1       0.86      0.95      0.90        91

    accuracy                           0.90       184
   macro avg       0.90      0.90      0.90       184
weighted avg       0.90      0.90      0.90       184

[[79 14]
 [ 5 86]]


In [ ]:
from sklearn.svm import SVC
print("SVC")
svm = SVC(kernel='sigmoid', C=1.0, random_state=2)
svm.fit(X_train,y_train)
y_pred=svm.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))


SVC
              precision    recall  f1-score   support

           0       0.94      0.85      0.89        93
           1       0.86      0.95      0.90        91

    accuracy                           0.90       184
   macro avg       0.90      0.90      0.90       184
weighted avg       0.90      0.90      0.90       184

[[79 14]
 [ 5 86]]


In [ ]:
# Splitting dataset into training and testing sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(rounded_predictions, target, test_size=0.20, shuffle=True)

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier
print("ETC")
b = ExtraTreesClassifier(n_estimators=300, random_state=5, max_depth=20)
b_pred = b.fit(X_train, y_train).predict(X_test)
print(classification_report(y_test,b_pred))
print(confusion_matrix(y_test,b_pred))

ETC
              precision    recall  f1-score   support

           0       0.83      0.85      0.84        73
           1       0.90      0.88      0.89       111

    accuracy                           0.87       184
   macro avg       0.86      0.87      0.86       184
weighted avg       0.87      0.87      0.87       184

[[62 11]
 [13 98]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
print("ADA")
xgb = AdaBoostClassifier(n_estimators=100, random_state=5)
xgb_pred = xgb.fit(X_train, y_train).predict(X_test)
print(classification_report(y_test,xgb_pred))
print(confusion_matrix(y_test,xgb_pred))

ADA
              precision    recall  f1-score   support

           0       0.79      0.79      0.79        73
           1       0.86      0.86      0.86       111

    accuracy                           0.84       184
   macro avg       0.83      0.83      0.83       184
weighted avg       0.84      0.84      0.84       184

[[58 15]
 [15 96]]


In [ ]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
r1 = LogisticRegression(random_state=1000, solver='saga',multi_class='ovr',C=2.0)
r2 = SVC(kernel='sigmoid', C=1.0, random_state=2, probability=True)
er = VotingClassifier([('lr', r1),('svc', r2)],voting="soft")

x=er.fit(X_train, y_train)

y_pred_class = er.predict(X_test)
print(classification_report(y_test,y_pred_class))
print(confusion_matrix(y_test,y_pred_class))


              precision    recall  f1-score   support

           0       0.82      0.85      0.83        73
           1       0.90      0.87      0.89       111

    accuracy                           0.86       184
   macro avg       0.86      0.86      0.86       184
weighted avg       0.87      0.86      0.86       184

[[62 11]
 [14 97]]


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
# 2. instantiate a logistic regression model
logreg = LogisticRegression(random_state=1000, solver='saga',multi_class='ovr',C=2.0)
# 3. train the model using X_train_dtm
x=logreg.fit(X_train, y_train)
# 4. make class predictions for X_test_dtm
y_pred_class = logreg.predict(X_test)
print(classification_report(y_test,y_pred_class))
print(confusion_matrix(y_test,y_pred_class))

              precision    recall  f1-score   support

           0       0.86      0.82      0.84        66
           1       0.84      0.88      0.86        72

    accuracy                           0.85       138
   macro avg       0.85      0.85      0.85       138
weighted avg       0.85      0.85      0.85       138

[[54 12]
 [ 9 63]]


In [ ]:
from sklearn.svm import SVC
print("SVC")
svm = SVC(kernel='sigmoid', C=2.0, random_state=2)
svm.fit(X_train,y_train)
y_pred=svm.predict(X_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))


SVC
              precision    recall  f1-score   support

           0       0.84      0.82      0.83        66
           1       0.84      0.86      0.85        72

    accuracy                           0.84       138
   macro avg       0.84      0.84      0.84       138
weighted avg       0.84      0.84      0.84       138

[[54 12]
 [10 62]]


In [ ]:
def nearest_on_circle(c, R, x):
    cos_=(x2-c2)/euclidean_dist(x1,x2,c1,c2)
    sin_=(x1-c1)/euclidean_dist(x1,x2,c1,c2)
    #then extrpolate the center along this line to a distance equal to that of radius
    #to obtain the nearest point
    y1=c1+r*cos_
    y2=c2+r*sin_
    y=y1,y2
    return y

In [ ]:
def euclidean_dist(x1,y1,x2,y2):
    return math.sqrt((x1-x2)**2 +(y1-y2)**2)

In [ ]:
def reflections_in_tunnel(w, h, alpha, n):
    x=(n*w-h)/math.tan(alpha)
    return x

In [ ]:
reflections_in_tunnel(2, 3, 30, 1)

0.15611995216165922

In [ ]:
def reflection_on_circle(c_x, R, alpha):
    #formula to find Sin Beta
    sinB=(c_x/R)*math.sin(alpha)
    # Now L will be
    L=c_x+(R*sinB)/(math.cos(alpha)*(1-2*math.sin(sinB)**2)-(2*math.sin(alpha)*math.sin(sinB))*(math.sqrt(1-math.sin(sinB)**2)))
    return L

In [ ]:
B=[[1,0],[1,0],[1,0]]
v=[1,2,2]
B=np.array(B)
v=np.array(v)



In [ ]:
import numpy as np
x = np.array([[0, 0, 1],
              [0, 1, 0],
              [1, 0, 0]])
y = ([[3.65], [1.55], [3.42]])
x = np.array(x)
scalars = np.linalg.solve(x, y)
scalars

array([[3.42],
       [1.55],
       [3.65]])

In [ ]:
from scipy.linalg import orth
o=orth(x)
v=scalars+o
v

array([[3.42, 3.42, 2.42],
       [1.55, 2.55, 1.55],
       [2.65, 3.65, 3.65]])

In [ ]:
def orthogonal_components(B, v):
    B = np.array(B)
    v = np.array(v)
    v11 = np.linalg.solve(x, y)
    from scipy.linalg import orth
    vp=orth(x)
    return v11,vp

In [ ]:
orthogonal_components(x,y)

(array([[3.42],
        [1.55],
        [3.65]]),
 array([[ 0.,  0., -1.],
        [ 0.,  1.,  0.],
        [-1.,  0.,  0.]]))

In [ ]:
def marginal_x(P):
    p=np.array(P)
    from scipy.stats.contingency import margins
    x, y = margins(p)
    return x.T

In [ ]:
import numpy as np


p = np.array([[0.01, 0.02, 0.04, 0.04],
                [0.03, 0.24, 0.15, 0.06],
                [0.04, 0.10, 0.08, 0.08],
                [0.02, 0.04, 0.03, 0.02]
            ])


a=marginal_x(p)
a=np.array(a)
print(marginal_x(p))

[[0.11 0.48 0.3  0.11]]


In [ ]:
def calc_Expectation(P):
		p=np.array(P)
		sum = 0
		from scipy.stats.contingency import margins
		x, y = margins(p)
		a=np.array(y.T)
		for i in range(len(a)):
			sum=sum+ (a[i])
		e=float(sum)
		return e



In [ ]:
def calc_Expectation(P):
		p=np.array(P)
		sum = 0
		from scipy.stats.contingency import margins
		x, y = margins(p)
		a=np.array(y.T)
		a=np.array(y.T)



In [ ]:
calc_Expectation(p)

1.0

In [ ]:
def calc_Expectation(P, n):
		prb = 1 / n
		sum = 0
		p=np.array(P)
		from scipy.stats.contingency import margins
		x, y = margins(p)
		a=np.array(x*y.T)


In [ ]:
p = np.array([[0.01, 0.02, 0.04, 0.04],
                [0.03, 0.24, 0.15, 0.06],
                [0.04, 0.10, 0.08, 0.08],
                [0.02, 0.04, 0.03, 0.02]
            ])


n=2
calc_Expectation(p,n)

0.1015

In [ ]:
def repeated_entries(x):
    a=np.array(x.T)
    N = len(x)
    L=len(a)
    S = np.zeros((N, L))
    u = a
    return S, u

x=np.array([3,4,4,5,6,7])
repeated_entries(x)

(array([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]),
 array([3, 4, 4, 5, 6, 7]))